### ISSUE TITLE
positional/3d audio support

### ISSUE THREAD

**Issue by fastfinge** [mltony/nvda-phonetic-punctuation#22]
Is there any chance of getting audio panning based on the position of the control on-screen, the way both Mac OS and the unspoken addon do it? This is my primary use case, to make sure items are positioned where I expect them to be. Sadly, earcons can't replace this use case for me. Earcons is a much better and much more powerful addon, but I just really depend on that feature. If unspoken stops working I either fix it, or when it can't be fixed, I guess I'll have to move to mac OS or something.

**Comment by mltony** [comment]
I don't plan to implement this. Unspoken used custom C++ audio libraries that implement 3d sound which caused many side effects including crashes. I have neither expertise nor time to revive these libraries.
BTW from your comment - do you mean that unspoken is still working for you? Could you share a working version for me? I did an investigation a couple of years ago and I was under impression that Unspoken was abandoned - there were 4 or 5 different versions but none of them worked with recent version of NVDA. Wondering if anyone else managed to revive Unspoken in the meantime?

**Comment by fastfinge** [comment]
I fix this one whenever it breaks:
https://github.com/masonasons/Unspoken/releases

Mason isn't working on it, but accepts my pull requests. So we keep it working for now. It's still using the terrible 3d Audio Library, so still has all of the bugs associated with it. But I depend on it, so I'm stuck.
