### ISSUE TITLE
constant "variable 'prosodyOffset' referenced before assignment" errors

### ISSUE THREAD

**Issue by aefren** [mltony/nvda-phonetic-punctuation#5]
This message error appears always, making impossible create new rules or even test the already created rules with the test button. 

This problem does not affects rules previously created.

Complete message error: 
"Audio rule Error  Error creating audio rule: local variable 'prosodyOffset' referenced before assignment

NVDA version: 2020.4
Phonetic Punctuation and Audio Rules version is 1.3

**Comment by mltony** [comment]
Fixed in v1.4.
